### ISSUE TITLE
Learn more about static IPs

### ISSUE THREAD

**Issue by jd-apprentice** [jd-apprentice/jd-server#30]

**Comment by jd-apprentice** [comment]
So about the issue #7 the idea was that when lights went out I have some sort of plan, the pi's itself are now using the DNS

node00.local
node01.local
node02.local
node03.local

Which is refered to an IP in the `/etc/hosts` and I've noticed that even if you format the MicroSD they assign the same IP as before so no issues with that.

About the containers in the servers I was doing something like this:

```yml
version: "3.8"

services:

  dashdot:
    image: mauricenino/dashdot
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - "/:/mnt/host:ro"
    privileged: true
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
    networks:
      lan:
         ipv4_address: 10.5.0.11

  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    privileged: true
    restart: unless-stopped
    environment:
      CONTAINERS: 1
      INFO: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "2375:2375"

networks:
  lan:
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
```

But.. It's far better to expose via the tunnels with `node<number>local:<external_port>`
