### ISSUE TITLE
Investigate security measures

### ISSUE THREAD

**Issue by jd-apprentice** [jd-apprentice/jd-server#34]
Something like 

https://github.com/carlospolop/PEASS-ng/tree/master/linPEAS

**Comment by jd-apprentice** [comment]
Found some things, I'll may change a few things after the cluster is created.

**Comment by jd-apprentice** [comment]
https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html Trying to check on this

**Comment by jd-apprentice** [comment]
I've been improving at security in docker with @shkz-x

Containers are now running something like this

```yml
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    user: 1000:1000
    container_name: homepage
    restart: always
    security_opt:
      - seccomp:~/security/default.json
      - no-new-privileges:true
    ports:
      - 4000:3000
    volumes:
      - ./links/config:/app/config
```

I'm going to close this one and open a new one for hardening in general.
