### ISSUE TITLE
Update docker in all machines

### ISSUE THREAD

**Issue by jd-apprentice** [jd-apprentice/jd-server#61]

**Comment by jd-apprentice** [comment]
Trying the following playbook

```yml
---
- name: install docker
  hosts: all
  become: yes
  vars_prompt:

    - name: "is_update"
      prompt: "Are you upgrading? (yes/no)"
      default: "no"
      private: no

  tasks:
    - name: Run apt-get update
      become: yes
      apt: update_cache=yes
    
    - name: Install curl
      become: yes
      apt: name=curl state=present

    - name: Run curl command
      become: yes
      shell: curl -fsSL test.docker.com -o get-docker.sh && sh get-docker.sh

    - name: Add user to docker group
      become: yes
      shell: usermod -aG docker $USER
      when: is_update == 'no'
```
